---
services:
  nginx:
    image: nginx
    volumes:
    - ./swatch-metrics.conf:/etc/nginx/conf.d/swatch-metrics.conf.template
    ports:
    - "8000:8080"
    environment:
    - SERVICE_NAME=swatch-metrics-service
    - PUBLIC_API_SERVER=localhost
    - PUBLIC_API_PORT=8000
    # swatch-subscription-sync-service.rhsm-stage.svc.cluster.local
    - PRIVATE_API_SERVER=127.0.0.1
    # just 9000 for the sake of confirming that /internal URLs are proxying to a different place than the rest
    - PRIVATE_API_PORT=9000
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/swatch-metrics.conf.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"